# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sml_auction', '0002_auction_current_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions_success', to=settings.AUTH_USER_MODEL, verbose_name='Winner'),
        ),
    ]
