# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sml_auction', '0003_auction_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Finished'),
        ),
    ]
